# Generated by Django 5.1.2 on 2025-02-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='blogs',
        ),
    ]
