# Generated by Django 5.1.2 on 2025-02-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='blog_users',
        ),
    ]
