# Generated by Django 5.1.2 on 2025-02-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'managed': True},
        ),
    ]
