# Generated by Django 5.1.2 on 2025-02-02 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_user_blogs_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='user_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
