# Generated by Django 5.1.2 on 2025-02-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogs_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='user_id',
            new_name='user',
        ),
    ]
