# Generated by Django 5.1.2 on 2025-02-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogs_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='user',
            new_name='user_id',
        ),
    ]
