# Generated by Django 5.1.2 on 2025-02-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_user_blogs_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='category',
            new_name='category_id',
        ),
    ]
