# Generated by Django 5.1.2 on 2025-02-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_category_blogs_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
    ]
