# Generated by Django 5.1.2 on 2025-02-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blogs_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='user_id',
            new_name='user',
        ),
    ]
